services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=procedureUser
      - MONGO_INITDB_ROOT_PASSWORD=PocoPocoPoco
volumes:
  data: {}