package com.java.procedure_spring_mongo_service;

public enum Categories {
//    Major Categories
    DIAGNOSTIC_AND_PREVENTIVE,
    RADIOGRAPHS,
    BASIC_SERVICE,
    MAJOR_RESTORATIVES,
    PROSTHODONTICS,
    ORTHODONTICS,

//    Minor Categories
//    FOR DIAGNOSTIC_AND_PREVENTIVE
    ORAL_EXAMS,
    FLUORIDES,
    CLEANINGS,
    EMERGENCY_PALLIATIVE,
    SEALANT,

//    FOR RADIOGRAPHS
    BITEWINGS,
    FULL_MOUTH_RADIOGRAPHS,
    ALL_OTHER_RADIOGRAPHS,

//    FOR BASIC_SERVICE
    OTHER_RESTORATIVE,
    ENDODONTICS_ROOT_CANALS,
    ALL_OTHER_ENDODONTICS,
    MAJOR_PERIODONTICS,
    SIMPLE_PERIODONTICS,
    PERIODONTAL_PROPHYS,
    SIMPLE_EXTRACTIONS,
    COMPLEX_EXTRACTIONS,
    ALL_OTHER_ORAL_SURGERY,
    DENTURE_REPAIR,
    OTHER_ADJUNCTIVE,

//    FOR PROSTHODONTICS
    FIXED_BRIDGEWORK,
    PARTIAL_DENTURES,
    FULL_DENTURES,
    OTHER_DENTURES_AND_BRIDGES,

//    FOR MAJOR_RESTORATIVES AND ORTHODONTICS
    NOT_APPLICABLE


}
